name: Gen Keystore
on: workflow_dispatch
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - run: |
          keytool -genkey -v -keystore ts.jks -alias textscanner \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass textscanner123 -keypass textscanner123 \
            -dname "CN=TextScanner,O=Hanif,C=BD"
          echo "COPY BELOW LINE:"
          base64 -w 0 ts.jks
